apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paymentapi-deployment
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: paymentapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: paymentapi
    spec:
      containers:
      - image: payappcontainer.azurecr.io/paymentapi
        imagePullPolicy: Always
        name: paymentapi
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: payappsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
